# Setup
title:        under pressure
tagline:      collegiate cullinary creations
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kellie Carlson
  url:        http://carlsonkellie.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
